#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           0

bspc config focused_border_color "#CBA6FF"
bspc config presel_feedback_color "#CBA6FF"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config single_monocle		 true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# autostart programs
~/.config/polybar/launch.sh &
greenclip daemon &
picom -b &
# feh --bg-fill <image>
